In [9]:
import pandas as pd

In [16]:
days  = ["Mon", "Tue", "Wed", "Thu", "Fri"]
temps = [22.5, 18.0, 25.3, 30.1, 19.8]

df1  =  pd.Series(data=temps,
            index=days,
            name='Temp Data').to_frame().astype(int)

display(df1)

     Temp Data
Mon         22
Tue         18
Wed         25
Thu         30
Fri         19

In [24]:
df1.isna()

     Temp Data
Mon      False
Tue      False
Wed      False
Thu      False
Fri      False